--INSERT TABELA DIC_ESCOLA

INSERT INTO DIC_ESCOLA (ID_DIC,DIC_TPM_ADM_ESCOLA,DIC_TIPO_LOCALIZACAO,DIC_SIT_FUNC_ESCOLAR) VALUES ('1','FEDERAL','URBANA','EM ATIVIDADE');
INSERT INTO DIC_ESCOLA (ID_DIC,DIC_TPM_ADM_ESCOLA,DIC_TIPO_LOCALIZACAO,DIC_SIT_FUNC_ESCOLAR) VALUES ('2','ESTADUAL','RURAL','PARALISADA');
INSERT INTO DIC_ESCOLA (ID_DIC,DIC_TPM_ADM_ESCOLA,DIC_TIPO_LOCALIZACAO,DIC_SIT_FUNC_ESCOLAR) VALUES ('3','MUNICIPAL','NULL','EXTINTA');
INSERT INTO DIC_ESCOLA (ID_DIC,DIC_TPM_ADM_ESCOLA,DIC_TIPO_LOCALIZACAO,DIC_SIT_FUNC_ESCOLAR) VALUES ('4','PRIVADA','NULL','ESCOLA EXTINTA EM ANOS ANTERIORES');

--INSERT TABELA DIC_NECESSIDADES_ESPECIAIS

INSERT INTO DIC_NECESSIDADES_ESPECIAIS (ID_DIC, DIC_RESPOSTA) VALUES ('0', 'NÃO');
INSERT INTO DIC_NECESSIDADES_ESPECIAIS (ID_DIC, DIC_RESPOSTA) VALUES ('1', 'SIM');