INSERT INTO COR (cod_cor, nome_cor) VALUES (235, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (236, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (237, 'BRANCO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (238, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (252, 'BRANCO - ADAPTADA (BRAILE E LEDOR)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (275, 'AZUL (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (276, 'AMARELO (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (277, 'BRANCO (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (278, 'ROSA (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (231, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (232, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (233, 'BRANCO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (234, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (251, 'BRANCO - ADAPTADA (BRAILE E LEDOR)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (271, 'AZUL (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (272, 'AMARELO (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (273, 'BRANCO (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (274, 'ROSA (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (239, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (240, 'CINZA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (241, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (242, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (253, 'CINZA - ADAPTADA (BRAILE E LEDOR)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (279, 'AMARELO (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (280, 'CINZA (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (281, 'AZUL (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (282, 'ROSA (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (243, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (244, 'CINZA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (245, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (246, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (254, 'CINZA - ADAPTADA (BRAILE E LEDOR)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (283, 'AMARELO (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (284, 'CINZA (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (285, 'AZUL (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (286, 'ROSA (REAPLICAÇÃO)');
