from script_limpeza import tirar_null

arquivoentrada = open('microdados_enem_2015.csv', 'r')
arquivosaida = open('t_preenche_2015.csv', 'w')

for i in arquivoentrada:
    texto = i.split(",")

    arquivosaida.writelines(texto[0] + "," + "1," + texto[120] + "\n")
    arquivosaida.writelines(texto[0] + "," + "2," + texto[116] + "\n")
    arquivosaida.writelines(texto[0] + "," + "3," + texto[117] + "\n")
    arquivosaida.writelines(texto[0] + "," + "4," + texto[121] + "\n")
    arquivosaida.writelines(texto[0] + "," + "7," + texto[141] + "\n")
    arquivosaida.writelines(texto[0] + "," + "8," + texto[134] + "\n")
    arquivosaida.writelines(texto[0] + "," + "9," + texto[135] + "\n")
    arquivosaida.writelines(texto[0] + "," + "11," + texto[139] + "\n")
    arquivosaida.writelines(texto[0] + "," + "12," + texto[125] + "\n")
    arquivosaida.writelines(texto[0] + "," + "13," + texto[129] + "\n")
    arquivosaida.writelines(texto[0] + "," + "14," + texto[127] + "\n")
    arquivosaida.writelines(texto[0] + "," + "15," + texto[128] + "\n")
    arquivosaida.writelines(texto[0] + "," + "16," + texto[138] + "\n")
    arquivosaida.writelines(texto[0] + "," + "17," + texto[137] + "\n")
    arquivosaida.writelines(texto[0] + "," + "18," + texto[140] + "\n")
    arquivosaida.writelines(texto[0] + "," + "19," + texto[136] + "\n")
    arquivosaida.writelines(texto[0] + "," + "20," + texto[133] + "\n")
    arquivosaida.writelines(texto[0] + "," + "21," + texto[122] + "\n")
    arquivosaida.writelines(texto[0] + "," + "22," + texto[123] + "\n")
    arquivosaida.writelines(texto[0] + "," + "23," + texto[149] + "\n")
    arquivosaida.writelines(texto[0] + "," + "24," + texto[155] + "\n")
    arquivosaida.writelines(texto[0] + "," + "25," + texto[156] + "\n")
    arquivosaida.writelines(texto[0] + "," + "26," + texto[150] + "\n")
    arquivosaida.writelines(texto[0] + "," + "27," + texto[151] + "\n")
    arquivosaida.writelines(texto[0] + "," + "28," + texto[152] + "\n")
    arquivosaida.writelines(texto[0] + "," + "29," + texto[153] + "\n")
    arquivosaida.writelines(texto[0] + "," + "31," + texto[160] + "\n")
    arquivosaida.writelines(texto[0] + "," + "32," + texto[157] + "\n")
    arquivosaida.writelines(texto[0] + "," + "34," + texto[165])
    arquivosaida.writelines(texto[0] + "," + "35," + texto[162] + "\n")
    arquivosaida.writelines(texto[0] + "," + "40," + texto[142] + "\n")
    arquivosaida.writelines(texto[0] + "," + "41," + texto[143] + "\n")
    arquivosaida.writelines(texto[0] + "," + "42," + texto[144] + "\n")
    arquivosaida.writelines(texto[0] + "," + "43," + texto[145] + "\n")
    arquivosaida.writelines(texto[0] + "," + "44," + texto[146] + "\n")
    arquivosaida.writelines(texto[0] + "," + "45," + texto[147] + "\n")
    arquivosaida.writelines(texto[0] + "," + "46," + texto[148] + "\n")

arquivoentrada.close()
arquivosaida.close()