INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (1,'Incluindo você, quantas pessoas moram atualmente em sua residência?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (2,'Até que série seu pai, ou o homem responsável por você, estudou?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (3,'Até que série sua mãe, ou a mulher responsável por você, estudou?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (4,'Qual é a renda mensal de sua família? (Some a sua renda com a dos seus familiares.)');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (5,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (6,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (7,'Você exerce ou já exerceu atividade remunerada?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (8,'Na sua residência tem televisão em cores?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (9,'Na sua residência tem aparelho de DVD?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (10,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (11,'Na sua residência tem computador?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (12,'Na sua residência tem carro?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (13,'Na sua residência tem máquina de lavar roupa (o tanquinho NÃO deve ser considerado)?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (14,'Na sua residência tem geladeira?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (15,'Na sua residência tem freezer (independente ou segunda porta da geladeira)?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (16,'Na sua residência tem telefone fixo?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (17,'Na sua residência tem telefone celular?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (18,'Na sua residência tem acesso à Internet?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (19,'Na sua residência tem TV por assinatura?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (20,'Na sua residência tem aspirador de pó?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (21,'Em sua residência trabalha empregado(a) doméstico(a)?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (22,'Na sua residência tem banheiro?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (23,'Indique os motivos que levaram você a participar do ENEM: Testar meus conhecimentos, para aumentar as minhas chances de ingressar na Educação Superior.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (24,'Indique os motivos que levaram você a participar do ENEM: Aumentar a possibilidade de conseguir um emprego.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (25,'Indique os motivos que levaram você a participar do ENEM: Progredir no meu emprego atual.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (26,'Indique os motivos que levaram você a participar do ENEM: Ingressar na Educação Superior pública.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (27,'Indique os motivos que levaram você a participar do ENEM: Ingressar na Educação Superior privada.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (28,'Indique os motivos que levaram você a participar do ENEM: Conseguir uma bolsa de estudos (ProUni, outras).');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (29,'Indique os motivos que levaram você a participar do ENEM: Participar do Programa de Financiamento Estudantil - FIES.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (30,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (31,'Durante o Ensino Fundamental, você abandonou os estudos e/ou foi reprovado?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (32,'Em que tipo de escola você frequentou o Ensino Fundamental?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (33,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (34,'Durante o Ensino Médio, você abandonou os estudos por algum tempo e/ou foi reprovado?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (35,'Em que tipo de escola você frequentou o Ensino Médio?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (36,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (37,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (38,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (39,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (40,'Com que idade você começou a exercer uma atividade remunerada?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (41,'Quantas horas semanais você trabalha ou trabalhava aproximadamente? (Considere a atividade remunerada mais recente.)');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (42,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Ajudar meus pais nas despesas com a casa.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (43,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Sustentar minha família (esposo/a, filhos/as etc.).');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (44,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Ser independente/ganhar meu próprio dinheiro.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (45,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Adquirir experiência.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (46,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Custear/pagar meus estudos.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (47,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (48,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (49,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (50,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (51,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (52,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (53,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (54,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (55,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (56,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (57,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (58,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (59,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (60,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (61,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (62,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (63,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (64,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (65,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (66,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (67,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (68,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (69,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (70,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (71,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (72,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (73,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (74,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (75,null);
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (76,null);
