INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (1,'Incluindo você, quantas pessoas moram atualmente em sua residência?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (2,'Até que série seu pai, ou o homem responsável por você, estudou?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (3,'Até que série sua mãe, ou a mulher responsável por você, estudou?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (4,'Qual é a renda mensal de sua família? (Some a sua renda com a dos seus familiares.)');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (5,'A residência de sua família é');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (6,'A residência de sua família está localizada em');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (7,'Você exerce ou já exerceu atividade remunerada?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (8,'Na sua residência tem televisão em cores?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (9,'Na sua residência tem aparelho de DVD?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (10,'Você tem em sua casa? Rádio');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (11,'Na sua residência tem computador?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (12,'Na sua residência tem carro?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (13,'Na sua residência tem máquina de lavar roupa (o tanquinho NÃO deve ser considerado)?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (14,'Na sua residência tem geladeira?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (15,'Na sua residência tem freezer (independente ou segunda porta da geladeira)?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (16,'Na sua residência tem telefone fixo?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (17,'Na sua residência tem telefone celular?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (18,'Na sua residência tem acesso à Internet?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (19,'Na sua residência tem TV por assinatura?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (20,'Na sua residência tem aspirador de pó?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (21,'Em sua residência trabalha empregado(a) doméstico(a)?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (22,'Na sua residência tem banheiro?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (23,'Indique os motivos que levaram você a participar do ENEM: Testar meus conhecimentos, para aumentar as minhas chances de ingressar na Educação Superior.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (24,'Indique os motivos que levaram você a participar do ENEM: Aumentar a possibilidade de conseguir um emprego.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (25,'Indique os motivos que levaram você a participar do ENEM: Progredir no meu emprego atual.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (26,'Indique os motivos que levaram você a participar do ENEM: Ingressar na Educação Superior pública.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (27,'Indique os motivos que levaram você a participar do ENEM: Ingressar na Educação Superior privada.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (28,'Indique os motivos que levaram você a participar do ENEM: Conseguir uma bolsa de estudos (ProUni, outras).');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (29,'Indique os motivos que levaram você a participar do ENEM: Participar do Programa de Financiamento Estudantil - FIES.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (30,'Quantos anos você levou para concluir o Ensino Fundamental?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (31,'Durante o Ensino Fundamental, você abandonou os estudos e/ou foi reprovado?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (32,'Em que tipo de escola você frequentou o Ensino Fundamental?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (33,'Quantos anos você levou para concluir o Ensino Médio?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (34,'Durante o Ensino Médio, você abandonou os estudos por algum tempo e/ou foi reprovado?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (35,'Em que tipo de escola você frequentou o Ensino Médio?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (36,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Pró-Uni (Programa Universidade para Todos)');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (37,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Bolsa de estudos da própria Instituição de Ensino Superior');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (38,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Bolsa de estudos da empresa onde trabalho');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (39,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Auxílio do Programa de Financiamento Estudantil - FIES');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (40,'Com que idade você começou a exercer uma atividade remunerada?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (41,'Quantas horas semanais você trabalha ou trabalhava aproximadamente? (Considere a atividade remunerada mais recente.)');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (42,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Ajudar meus pais nas despesas com a casa.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (43,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Sustentar minha família (esposo/a, filhos/as etc.).');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (44,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Ser independente/ganhar meu próprio dinheiro.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (45,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Adquirir experiência.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (46,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Custear/pagar meus estudos.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (47,'Indique os cursos que você frequenta ou frequentou: Curso profissionalizante');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (48,'Indique os cursos que você frequenta ou frequentou: Curso preparatório para vestibular');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (49,'Indique os cursos que você frequenta ou frequentou: Curso superior');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (50,'Indique os cursos que você frequenta ou frequentou: Curso de língua estrangeira');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (51,'Indique os cursos que você frequenta ou frequentou: Curso de computação ou informática');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (52,'Indique os cursos que você frequenta ou frequentou: Curso preparatório para concursos públicos');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (53,'Indique os cursos que você frequenta ou frequentou: Outro curso');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (54,'Você cursa ou já cursou a Educação de Jovens e Adultos – EJA?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (55,'Como é ou era o principal curso de EJA que você frequenta ou frequentou?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (56,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Trabalhava, não tinha tempo de estudar');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (57,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA,  vá para a questão...): Estudava no curso da empresa e foi interrompido');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (58,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA,  vá para a questão...): Ocorreram problemas de saúde ou acidentes comigo ou familiares');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (59,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA,  vá para a questão...): Mudei de bairro,  cidade ou município');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (60,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Por motivos pessoais, casamento, filhos etc.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (61,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA,  vá para a questão...): Faltava-me interesse,  desisti');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (62,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA,  vá para a questão...): Senti-me discriminado(a)');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (63,'Você já frequentou o ensino regular?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (64,'Indique o que levou você a deixar de cursar o ensino regular: Falta de vaga em escola pública');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (65,'Indique o que levou você a deixar de cursar o ensino regular: Ausência de escola perto de casa');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (66,'Indique o que levou você a deixar de cursar o ensino regular: Falta de interesse em estudar');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (67,'Indique o que levou você a deixar de cursar o ensino regular: Trabalho,  falta de tempo para estudar');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (68,'Indique o que levou você a deixar de cursar o ensino regular: Motivos pessoais,  casamento/filhos etc.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (69,'Indique o que levou você a deixar de cursar o ensino regular: Falta de apoio familiar.');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (70,'Indique o que levou você a deixar de cursar o ensino regular: Problemas de saúde ou acidente comigo ou familiares');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (71,'Indique o que levou você a deixar de cursar o ensino regular: Discriminação/Preconceitos (sexo, raça, idade, classe etc.)');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (72,'Quantos anos você tinha quando deixou de frequentar o ensino regular?');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (73,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA,  vá para a questão...): Temi/Sofri violência');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (74,'Indique o que levou você a deixar de cursar o ensino regular: Dificuldades após reprovação');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (75,'Indique o que levou você a deixar de cursar o ensino regular: Falta de condições adequadas na escola');
INSERT INTO QUESTAO_SOCIOECONOMICO (sequencial_questionario_socio,questao) VALUES (76,'Indique o que levou você a deixar de cursar o ensino regular: Medo de sofrer violência');
